import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Footer from '../components/Footer'
import Section from '../components/Section'
import Link from 'next/link'
import profilePic from '../public/img/SuiteD-KitchenUpgrade1.png'
import Hero from '../components/Hero'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <Hero
      alt="Pic"
      image="/img/SuiteD-KitchenUpgrade1.png"

      >

Image Component
   <br />
   as a Background
      </Hero>

      <Section anchor="overview" contrast="dark">
        <h2 className="display_h2 here">HERE</h2>
        <div className="head_underline"></div>

        <h3 className="display_h3 max-w-[700px] mb-4">
          Live. Work. Relax.&nbsp;Play. testing some longer text PlaP PLay
        </h3>

        <p className="text-base max-w-[580px]">
          The Residences on Kennedy Circle comprises of 148 units in a 6-storey
          mid-rise state-of-the-art building that embodies a distinct spirit and
          style like no other condominium in the area. The building features 1
          bedroom, 1 bedroom + den and 2 bedroom unit types. Each unit has been
          carefully developed to suit a variety of lifestyles with convenience
          and comfort in mind, and appointed with beautiful, timeless features
          and finishes.
        </p>

        <Link href="/">
          <a className="cta">VIEW FLOORPLANS</a>
        </Link>
      </Section>





      <Footer></Footer>
    </>
  );
}
