import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Footer from "../components/Footer";
import Section from "../components/Section";
import Link from "next/link";
import profilePic from "../public/img/SuiteD-KitchenUpgrade1.png";
import Hero from "../components/Hero";
import FlyoutMenu from "../components/Plans";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero alt="Pic" image="/img/SuiteD-KitchenUpgrade1.png">
        Image Component
        <br />
        as a Background
      </Hero>

      <Section anchor="overview" contrast="dark">
        <h2 className="display_h2 here">HERE</h2>
        <div className="head_underline"></div>

        <h3 className="display_h3 max-w-[700px] mb-4">
          Live. Work. Relax.&nbsp;Play. testing some longer text PlaP PLay
        </h3>

        <p className="text-base max-w-[580px]">
          The Residences on Kennedy Circle comprises of 148 units in a 6-storey
          mid-rise state-of-the-art building that embodies a distinct spirit and
          style like no other condominium in the area. The building features 1
          bedroom, 1 bedroom + den and 2 bedroom unit types. Each unit has been
          carefully developed to suit a variety of lifestyles with convenience
          and comfort in mind, and appointed with beautiful, timeless features
          and finishes.
        </p>

        <Link href="/">
          <a className="cta">VIEW FLOORPLANS</a>
        </Link>
      </Section>

      <FlyoutMenu />

      <div className="container mx-auto ">
        <div className="flex flex-col md:flex-row">
         
          <div className="details w-[300px]">
            <img
              src="/img/icon/KC-Site-FloorPlan-Modal-TransparentBG-A.svg"
              width={150}
            />

            <hr className=" h-[2px] border-t-[2px] border-gray-900 mb-10 mt-4"></hr>
            <span className="display_h3 block text-gray-900">1 BED</span>
            <span className="display_h3 block text-gray-900">1 BATH</span>

            <dl>
              <div className=" py-1 sm:grid sm:grid-cols-2 sm:gap-4 ">
                <dt className="text-sm font-medium text-gray-900">
                  Indoor living
                </dt>
                <dd className="mt-1 text-sm text-gray-500 sm:mt-0  text-right">
                  606 sqft.
                </dd>
              </div>

              <div className=" py-1 sm:grid sm:grid-cols-2 sm:gap-4 ">
                <dt className="text-sm font-medium text-gray-900">
                  Outdoor living
                </dt>
                <dd className="mt-1 text-sm text-gray-500 sm:mt-0 text-right">
                  51 sqft.
                </dd>
              </div>
              <div className=" py-1 sm:grid sm:grid-cols-2 sm:gap-4 ">
                <dt className="text-sm font-medium text-gray-900">Total</dt>
                <dd className="mt-1 text-sm text-gray-500 sm:mt-0 text-right">
                  657 sqft.
                </dd>
              </div>
            </dl>

            <Link href="/">
              <a className="cta">DOWNLOAD</a>
            </Link>
          </div>

          <div className="fplan grow text-right">
            <img
              src="/img/floorplans/KC-Site-FloorPlan-Modal-TransparentBG-A.png"
              width="400"
              className="pl-40 pb-40 w-full"
            />
          </div>
        </div>
      </div>

      <Footer></Footer>
    </>
  );
}
