import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Footer from "../components/Footer";
import Section from "../components/Section";
import Link from "next/link";
import profilePic from "../public/img/SuiteD-KitchenUpgrade1.png";
import Hero from "../components/Hero";
import Registration from "../components/Registration";
import { Fragment } from 'react'
import { Tab } from '@headlessui/react'
import Menu from '../components/Menu'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu></Menu>
      <Hero alt="Pic" image="/img/SuiteD-KitchenUpgrade1.png">
        Image Component
        <br />
        as a Background
      </Hero>

      <Section anchor="overview" contrast="light">
        <div className="flex flex-row">
          <div className="max-w-[580px]">
            <h2 className="display_h2 here">HERE</h2>
            <div className="head_underline"></div>
            <h3 className="display_h3 max-w-[700px] mb-4">
            You're living a sustainable and eco-conscious lifestyle.
            </h3>

            <p className="text-base max-w-[580px]">
            We've committed to bring sustainable design and environmentally-responsible features, amenities and technology throughout the building. <br/>
<br/>

            </p>

         
          </div>
        </div>
      </Section>
     
     
      <div className="img_break">
        <img
          src="/img/SuiteD-KitchenUpgrade1.png"
          alt="Picture of the author"
        />
      </div>



      <Section anchor="overview" contrast="dark">
        <div className="flex flex-row">
          <div className="w-full">
            <h2 className="display_alt  text-center">FEATURES & FINISHES</h2>
            <div className="head_underline "></div>

            <div className="w-4/5 m-auto grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-2 gap-10 lg:gap-20 pt-10  ">
              <div>
                <img
                  className="h-[182px] mb-[70px]"
                  src="img/icon/KC-Site-Green-Icons-1-HeatingandCooling.svg"
                />
                <h3 className="text-xl mb-6">Heating & Cooling</h3>
                <p>
                Efficient distribution of heating and cooling through sealed duct work which lowers the usage of energy, as well as the installation of an Energy Recovery Ventilator (ERV) resulting in healthier, fresh air intake, improved control of humidity and lowered use of energy.

                </p>
              </div>
              <div>
                <img
                  className="h-[182px] mb-[70px]"
                  src="img/icon/KC-Site-Green-Icons-2-Insulation.svg"
                />
                <h3 className="text-xl mb-6">Insulation</h3>
                <p>
                Tightly sealed building envelope and wall insulation to reduce heat loss and thermally insulated energy efficient double glazed architecturally designed windows with low expansion polyurethane spray foam for a tight air seal.

                </p>
              </div>
              <div>
                <img
                  className="h-[182px] mb-[70px]"
                  src="img/icon/KC-Site-Green-Icons-3-ElectricalandPlumbing.svg"
                />
                <h3 className="text-xl mb-6">Electrical & Plumbing</h3>
                <p>
                Individually metered suites to lower costs to utility bills and
high efficiency plumbing fixtures with central hot water delivery system installed throughout building and in suites for water conservation. 

                </p>
              </div>
              <div>
                <img
                  className="h-[182px] mb-[70px]"
                  src="img/icon/KC-Site-Green-Icons-4-Recycling.svg"
                />
                <h3 className="text-xl mb-6">Recycling</h3>
                <p>
                Community Recycling and Waste Reduction Program with centralized disposal facilities with separate water 

                </p>
              </div>
           
            </div>

         
          </div>
        </div>
      </Section>


  

      <Section anchor="overview" contrast="light">
        <div className="flex flex-row">
          <div className="w-full">
            <h2 className="display_alt  text-center">EV CHARGING</h2>
            <div className="head_underline "></div>

            Two options offered for EV Charging:

            <Tab.Group>
      <Tab.List>
        <Tab as={Fragment}>
          {({ selected }) => (
            <button
              className={
                selected ? 'bg-blue-500 text-white' : 'bg-white text-black'
              }
            >
              Tab 1
            </button>
          )}
        </Tab>
        <Tab as={Fragment}>
          {({ selected }) => (
            <button
              className={
                selected ? 'bg-blue-500 text-white' : 'bg-white text-black'
              }
            >
              Tab 2
            </button>
          )}
        </Tab>
     
      </Tab.List>
      <Tab.Panels>
        <Tab.Panel>
        EV Charging Rough-In to facilitate future installation of EV Charging Capability
<ul>
  <li>
  Offers an Installation of electrical conduit running to sub-electrical room to facilitate future installation of EV Charge capabilities

  </li>
  <li>
  To be managed by Property Management and Condominium Corporation after closing. Agreement to be provided and signed by resident/owner

  </li>
</ul>

        </Tab.Panel>

        <Tab.Panel>
        OPTION 2 EV Charging Rough-In to facilitate future installation of EV Charging Capability
<ul>
  <li>
  Offers an Installation of electrical conduit running to sub-electrical room to facilitate future installation of EV Charge capabilities

  </li>
  <li>
  To be managed by Property Management and Condominium Corporation after closing. Agreement to be provided and signed by resident/owner

  </li>
</ul>
        </Tab.Panel>

      </Tab.Panels>
    </Tab.Group>


    <div className="here_img">
          <img
            src="/img/SuiteD-KitchenUpgrade1.png"
            alt="Picture of the author"
          />
        </div>

         
          </div>
        </div>
      </Section>


      




 

      <Registration></Registration>
      <Footer></Footer>
    </>
  );
}
