import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Footer from '../components/Footer'
import Section from '../components/Section'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <Section
      anchor="live"
      contrast="dark"
      >
<h2 className="font-sans text-8xl here">HERE</h2>
<div className=" w-full h-[2px] mb-7 block head_underline"></div>

<h3 className="font-sans text-5xl max-w-[700px] mb-4">Live. Work. Relax.&nbsp;Play.</h3>
<p className="text-base max-w-[580px]">
The Residences on Kennedy Circle comprises of 148 units in a 6-storey mid-rise state-of-the-art building that embodies a distinct spirit and style like no other condominium in the area. The building features 1 bedroom, 1 bedroom + den and 2 bedroom unit types. Each unit has been carefully developed to suit a variety of lifestyles with convenience and comfort in mind, and appointed with beautiful, timeless features and finishes. 
</p>

<a className="font-display inline-block text-cta mt-16" href="#">VIEW FLOORPLANS</a>

      </Section>

      <Section
      anchor="excel"
      contrast="light"
      >
<h2 className="font-sans text-8xl here ">HERE</h2>
<div className=" w-full h-[2px] mb-7 block head_underline"></div>

<h3 className="font-sans text-5xl max-w-[700px] mb-4">Live. Work. Relax.&nbsp;Play.</h3>
<p className="text-base max-w-[580px]">
The Residences on Kennedy Circle comprises of 148 units in a 6-storey mid-rise state-of-the-art building that embodies a distinct spirit and style like no other condominium in the area. The building features 1 bedroom, 1 bedroom + den and 2 bedroom unit types. Each unit has been carefully developed to suit a variety of lifestyles with convenience and comfort in mind, and appointed with beautiful, timeless features and finishes. 
</p>

<a className="font-display inline-block text-cta mt-16" href="#">VIEW FLOORPLANS</a>

<img className="bl-round" src="/SuiteD-KitchenUpgrade1.png"/>


      </Section>


      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
      <Footer></Footer>
    </>
  )
}
